# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77f936956397f68b5c712c5f420680106004b8276880d58661faa2007a1a7b27000ff8f04fe2aedd178721ab7d01aeacaeb4d1416a7eff220ba72ccb007acc08

test:
  secret_key_base: b779fe94c3d80298ebc2c8d9476e2fd9ad4c8c28bbf3e0cfdc5c5d4c3b650c3d8137aef1b50cba8fce771b16568a0eb4437670b49a1fdd376aabbda75a9f9ec7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
